# Numpy

In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Arreglos

In [3]:
arr= np.array([1,2,3])

print(arr)

[1 2 3]


In [31]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr = np.array([1,2,3,4,5,6], ndmin = 3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [7]:
arr =np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [8]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr = np.random.rand(3,3)

print(arr)

[[0.19922487 0.33870838 0.99442049]
 [0.06774573 0.22856039 0.64064745]
 [0.3898502  0.38206262 0.03009813]]


## Operaciones

In [27]:
arr1=[1,2,3]

arr2=[4,5,6]

arr3= np.add(arr1, arr2)

print(arr3)

[5 7 9]


In [28]:
arr1=[1,2,3]

arr2=[4,5,6]

arr3= np.subtract(arr2, arr1)

print(arr3)

[3 3 3]


In [29]:
arr1=[1,2,3]

arr2=[4,5,6]

arr3= np.multiply(arr2, arr1)

print(arr3)

[ 4 10 18]


In [13]:
arr1=[1,2,3]

arr2=[4,5,6]

arr3= np.divide(arr2, arr1)

print(arr3)

[4.  2.5 2. ]


# Agregación

In [41]:
arr=[1,5,7]
media =np.mean(arr)
print(media)

4.333333333333333


In [42]:
arr=[1,5,7]
mediana =np.median(arr)
print(mediana)

5.0


In [43]:
arr=[1,5,7]
maximo =np.max(arr)
print(maximo)

7


In [16]:
arr=[1,5,7]
minimo =np.min(arr)
print(minimo)

1


## Indexación

In [21]:
arr = np.array([1,2,3,4,5,6])

print(arr[0])

1


In [18]:
arr = np.array([1,2,3,4,5,6])

print(arr[-1])

6


In [40]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)
print(arr[1,2])

[[1 2 3]
 [4 5 6]]
6


## Slicing

In [22]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4])

[2 3 4]


In [23]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4:2])# Lo recorre de dos en dos

[2 4]


In [26]:
arr = np.array([1,2,3,4,5,6])

print(arr[::2])

[1 3 5]
